### ISSUE TITLE
Memory file broken, no metadata

### ISSUE THREAD

**Issue by AWAS666** [kagisearch/vectordb#5]
Ever since the change that split the metadata from the embeddings, it can't be loaded from disk anymore, as only the embeddings get saved an not the metadata.

This makes everything work just fine when using it from Ram, but completely breaks as soon as you try to load from storage.

Not sure what is a clean solution here, as saving two files would also be a hassle...

We could make a single dictionary outa the two of them when saving and splitting again once loaded?

**Comment by vprelovac** [comment]
I see what you mean. Splitting them made a lot of sense from resource usage/performance standpoint but this was overlooked.

Two dicts make sense, want to give it a shot?

**Comment by AWAS666** [comment]
> I see what you mean. Splitting them made a lot of sense from resource usage/performance standpoint but this was overlooked.
> 
> Two dicts make sense, want to give it a shot?

ye sure if that works out for you.
